#!/bin/bash
#SBATCH --partition=common
#SBATCH --cpus-per-task=1
#SBATCH --mem=64GB
#SBATCH --time=1-00:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=rss10@duke.edu
#SBATCH --job-name=lgcp_ll
#SBATCH --output=out/lgcp_ll_%A_%x.log

# =============================================================================
# aci_ll.sh — Posterior log-likelihood trace for one buoy (03_loglikLGCPSE.R).
#
# Feeds the burn-in traceplot generated by 03_sumLoglik.R. Kept distinct from
# the benchmark's aci_loglik.sh (which replays LL across GP-resolution combos).
#
# Usage (one job per buoy):
#   sbatch --export=ALL,BUOY=ns01  aci_ll.sh
#   sbatch --export=ALL,BUOY=ns02  aci_ll.sh
#   sbatch --export=ALL,BUOY=cox01 aci_ll.sh
# =============================================================================

module purge
module load PROJ/6.3.2-rhel8
module load GDAL/3.2.1-rhel8
module load GEOS/3.9.1-rhel8
module load Boost/1.75-rhel8
module load R/4.1.1-rhel8

cd $SLURM_SUBMIT_DIR

srun Rscript 03_loglikLGCPSE.R
